# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
require 'fileutils'

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  lane :release do
  gradle(task: "clean bundleRelease")
  end


  desc "Build release"
  lane :build do
    gradle(task: "assembleDebug")
  end

  lane :debug do
  gradle(task: "assembleDebug")
  
  # Debug: Print all APK paths
  puts "All APK paths: #{lane_context[SharedValues::GRADLE_ALL_APK_OUTPUT_PATHS]}"
  
  # Find the debug APK
  apk_path = lane_context[SharedValues::GRADLE_ALL_APK_OUTPUT_PATHS].find { |p| p.include?("debug") }
  puts "Copying from: #{apk_path}"
  
  # Force overwrite
  File.delete("debug.apk") if File.exist?("debug.apk")
  
  # Copy the new APK
  FileUtils.cp(apk_path, "debug.apk")
  puts "✅ Copied to: #{File.absolute_path('debug.apk')}"
end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
