// <auto-generated />
using System;
using MatthewsApp.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MatthewsApp.API.Migrations
{
    [DbContext(typeof(MatthewsAppDBContext))]
    [Migration("20230512063041_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MatthewsApp.API.Models.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActualDevice")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualDeviceAlias")
                        .HasColumnType("nvarchar(564)");

                    b.Property<DateTime>("ActualEndTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("ActualFacility")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActualStartTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ClientCaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ContainerSize")
                        .HasColumnType("int");

                    b.Property<int>("ContainerType")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Electricity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Fuel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsObsolete")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("PerformedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScheduledDevice")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScheduledDeviceAlias")
                        .HasColumnType("nvarchar(564)");

                    b.Property<Guid>("ScheduledFacility")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ScheduledStartTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Cases");
                });
#pragma warning restore 612, 618
        }
    }
}
