// <auto-generated />
using System;
using MatthewsApp.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatthewsApp.API.Migrations
{
    [DbContext(typeof(MatthewsAppDBContext))]
    partial class MatthewsAppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MatthewsApp.API.Models.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActualDevice")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualDeviceAlias")
                        .HasColumnType("nvarchar(564)");

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid?>("ActualFacility")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ClientCaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ContainerSize")
                        .HasColumnType("int");

                    b.Property<int>("ContainerType")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Electricity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacilityStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Fuel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsObsolete")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("PerformedBy")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PhysicalId")
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ScheduledDevice")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScheduledDeviceAlias")
                        .HasColumnType("nvarchar(564)");

                    b.Property<Guid?>("ScheduledFacility")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ScheduledStartTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FacilityStatusId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("MatthewsApp.API.Models.FacilityStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("StatusIcon")
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("FacilityStatuses");
                });

            modelBuilder.Entity("MatthewsApp.API.Models.Case", b =>
                {
                    b.HasOne("MatthewsApp.API.Models.FacilityStatus", "FacilityStatus")
                        .WithMany()
                        .HasForeignKey("FacilityStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacilityStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
